version: '3'
services:
  elaborate:
    build: ./ # Dockerfileがあるディレクトリのパス
    image: elaborate/webpack # イメージを指定(IMAGEタグはコンテナ作成後docker ps -aで得られる)
    container_name: elaborate
    ports:
      - "0.0.0.0:8080:8080" # "ホストのポート:コンテナのポート"
    volumes:
      - ./src:/app/src
      - ./dist:/app/dist
      - ./package.json:/app/package.json
      - ./webpack.config.js:/app/webpack.config.js
    command: node_modules/.bin/webpack-dev-server --host 0.0.0.0 # コンテナ起動時に自動で叩かれるコマンド
