version: 2.1
jobs:
  test:
    docker:
      - image: shotayamazaki/cci-docker-primary:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install node modules
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - ~/cache
      # run tests!
      - run:
          name: ESLint
          command: |
            mkdir /tmp/test-results
            mkdir /tmp/test-results/eslint
            node_modules/.bin/eslint src/**/*.{ts,tsx} --quiet \
              --format junit \
              --output-file /tmp/test-results/eslint/results.xml
      - run:
          name: stylelint
          command: node_modules/.bin/stylelint 'src/**/*.css'
      # collect reports
      - store_test_results:
          path: /tmp/test-results/eslint

  deploy:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install node modules
          command: npm install
      - run:
          name: add .env file
          command: |
            echo "FIREBASE_API_KEY=$FIREBASE_API_KEY" > .env
            echo "FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN" >> .env
            echo "FIREBASE_DATABASE_URL=$FIREBASE_DATABASE_URL" >> .env
            echo "FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID" >> .env
            echo "FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET" >> .env
            echo "FIREBASE_MESSAGING_SENDER_ID=$FIREBASE_MESSAGING_SENDER_ID" >> .env
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - ~/cache
      - run:
          name: build with webpack
          command: npm run build
      - run:
          name: deploy master to firebase hosting
          command: node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN

workflows:
  version: 2
  test_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
