export const blueBase: string
export const whiteBase: string
export const whiteBaseWithBorder: string
export const title: string
export const button: string
export const commit: string
export const checkDiff: string
export const signOut: string
export const auth: string
