import keyMirror from 'keymirror'

export const actionTypes = keyMirror({
  // Directory
  DIRECTORY__FIREBASE_REQUEST: null,
  DIRECTORY__FIREBASE_REQUEST_FAILURE: null,
  DIRECTORY_IS_VALID__FIREBASE_REQUEST: null,
  DIRECTORY_IS_VALID__FIREBASE_REQUEST_FAILURE: null,
  DIRECTORY__SET: null,
  DIRECTORY__ADD: null,
  DIRECTORY__CHECK_ID: null,
  DIRECTORY__SET_SELECTED_DIRECTORY_ID: null,

  // Branches
  BRANCH__FIREBASE_REQUEST: null,
  BRANCH__FIREBASE_REQUEST_FAILURE: null,
  BRANCH__SET: null,
  BRANCH__ADD: null,
  BRANCH__MERGE_OR_CLOSE: null,
  CURRENT_BRANCH_DATA__FIREBASE_REQUEST: null,
  CURRENT_BRANCH_DATA__FIREBASE_REQUEST_FAILURE: null,
  CURRENT_BRANCH_DATA__CHECK: null,

  // Commits
  COMMIT__FIREBASE_REQUEST: null,
  COMMIT__FIREBASE_REQUEST_FAILURE: null,
  COMMIT__ADD: null,
  LATEST_COMMIT_BODY__FIREBASE_REQUEST: null,
  LATEST_COMMIT_BODY__FIREBASE_REQUEST_FAILURE: null,
  LATEST_COMMIT_BODY__SET: null,

  // Modal
  MODAL__AUTHENTICATION_OPEN: null,
  MODAL__AUTHENTICATION_CLOSE: null,
})
