import keyMirror from 'keymirror'

export const actionTypes = keyMirror({
  // Directory
  DIRECTORY__FIREBASE_REQUEST: null,
  DIRECTORY__FIREBASE_REQUEST_FAILURE: null,
  DIRECTORY_IS_VALID__FIREBASE_REQUEST: null,
  DIRECTORY_IS_VALID__FIREBASE_REQUEST_FAILURE: null,
  DIRECTORY__SET: null,
  DIRECTORY__ADD: null,
  DIRECTORY__CHECK_ID: null,
  DIRECTORY__SET_SELECTED_DIRECTORY_ID: null,

  // Branches
  BRANCH__FIREBASE_REQUEST: null,
  BRANCH__FIREBASE_REQUEST_FAILURE: null,
  BRANCH__SET: null,
  BRANCH__ADD: null,
  BRANCH__MERGE_OR_CLOSE: null,
  CURRENT_BRANCH_DATA__FIREBASE_REQUEST: null,
  CURRENT_BRANCH_DATA__FIREBASE_REQUEST_FAILURE: null,
  CURRENT_BRANCH_DATA__CHECK: null,

  // Commits
  COMMIT__FIREBASE_REQUEST: null,
  COMMIT__FIREBASE_REQUEST_FAILURE: null,
  COMMIT__ADD: null,

  // Diff
  DIFF__FIREBASE_REQUEST: null,
  DIFF__FIREBASE_REQUEST_FAILURE: null,
  DIFF__LEFT_FILE_SET: null,
  DIFF__RIGHT_FILE_SET: null,
})
